version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 420cards
    ports:
      - '5432:5432'
