name: "Deploy"
on:
    push:
      branches: ["prod"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: working directory
        run: ssh staging 'cd 420cards-backend'

      - name: Check out the source
        run: ssh staging 'git checkout main'

      - name: pull
        run: ssh staging 'git pull'

      - name: shut down application
        run: ssh staging 'docker compose down'

      - name: start application
        run: ssh staging 'docker compose up -d'

      - name: clear docker cache
        run: ssh staging 'docker system prune --all --force'

 
            
